//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplicacionKermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_denominacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_denominacion()
        {
            this.tbl_arqueocaja_det = new HashSet<tbl_arqueocaja_det>();
        }
    
        public int id_denominacion { get; set; }
        
        [Display(Name = "Nombre de la moneda")]
        [Required(ErrorMessage = "Escoja el nombre de la moneda")]
        public int id_moneda { get; set; }
        [Display(Name = "Valor de la denominacion")]
        [Required(ErrorMessage = "Introduzca el valor numerico de la denominacion")]
        public decimal valor { get; set; }
        [Display(Name = "Valor en letras de la denominacion")]
        [Required(ErrorMessage = "Introduzca el valor de la denominacion en forma textual")]
        [StringLength(10, ErrorMessage = "La cantidad de caracteres permitida para este campo es de 250")]
        public string valor_letras { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_arqueocaja_det> tbl_arqueocaja_det { get; set; }
        public virtual tbl_moneda tbl_moneda { get; set; }
    }
}
