//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplicacionKermesse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_denominacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_denominacion()
        {
            this.tbl_arqueocaja_det = new HashSet<tbl_arqueocaja_det>();
        }
    
        public int id_denominacion { get; set; }
        [Display(Name = "Moneda")]
        [Required(ErrorMessage = "Seleccione una moneda valia")]
        public int id_moneda { get; set; }
        [Display(Name = "Valor de la Denominacion")]
        [Required(ErrorMessage = "Introduzca un valor Valido!")]
        public decimal valor { get; set; }
        [Display(Name = "Valor en Letras de la Denominacion")]
        [Required(ErrorMessage = "Introduzca un valor Valido!")]
        [StringLength(250, ErrorMessage = "ha excedido el numero de caracteres permitidos para este campo")]
        public string valor_letras { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_arqueocaja_det> tbl_arqueocaja_det { get; set; }
        public virtual tbl_moneda tbl_moneda { get; set; }
    }
}
